### ISSUE TITLE
failed in dashboard page

### ISSUE THREAD

**Issue by xiaoFine** [mengtao-code/tampermonkey-scripts#1]
Hi! 
The script worker in article detail page, but it failed in dashboard or feed list preview
![image](https://github.com/mengtao-code/tampermonkey-scripts/assets/12167470/72b95118-9e53-4579-9fa3-21f1a9da5876)

**Comment by dawnlightx123** [comment]
Hi, I fixed this bug in new version (0.0.5), so try it in [greasyfork](https://greasyfork.org/en/scripts/463461-fix-image-error-at-inoreader). I just tested the script with a [random weibo rss address](https://rsshub.app/weibo/user/2955896132). If you got the problem again, please give me your rss address, thank you.

**Comment by xiaoFine** [comment]
@mengtao-code  the errors are gone and now it works well! 
really appreciate！
